version: '3'
services:
  wordpress:
    image: wordpress:5.0.3
    ports:
      - 8888:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: test
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: 'root'
  secu:
    image: test:1
    environment:
      URL: wordpress:80/
    volumes:
      - ./docker:/secu